Customer registration, login, forgotpassword
Cezerin2/cezerin2-store pull request #7
Opened 2019-02-21 08:03 UTC by vamcart

#6

2019-02-21 08:10 UTC, vamcart commented
And here is the my working copy of this changes.
All works fine for me.
https://cezerin2.slack.com/files/UFVAW9HA4/FGCL59ETV/cezerin-customer-register-login-account.zip

2019-02-21 08:12 UTC, vamcart commented
To test new email templates, features, i have local smtp server.
Setup your smtp server at /config/server.js to test account activation, password recovery feature.

New email templates and options added to the "npm run setup"
/src/api/server/setup.js

2019-02-21 09:06 UTC, vamcart commented
If you have error when you click register button, try to clear cache in Chrome - Developer Console - Application - Clear storage - Clear site data.

actions.js:774 Uncaught (in promise) TypeError: Cannot read property 'retrieve' of undefined
in /src/store/shared/actions.js
:
export const registerUser = (data, callback) => async (dispatch, getState) => {
    const response = await api.ajax.register.retrieve(data);
    dispatch(handleRegisterProperties(response.json));
};
this string:
api.ajax.register.retrieve(data);

2019-02-22 14:20 UTC, LuBuss commented
Add a few missing files.
- you can create an account from the checkout

Work is still required in:
- Customer Login (have not tested)
- Customer Register (have not tested)

2019-02-22 14:57 UTC, LuBuss commented
I Verify all working

2019-02-22 16:18 UTC, vamcart commented
ok, merge this pr.

> I Verify all working

2019-02-22 21:05 UTC, LuBuss commented
Only verified working, but have not checked code.

2019-02-23 07:46 UTC, ngoyal16 requested changes

2019-02-23 07:46 UTC, ngoyal16 commented on src/server/index.js
> +app.get('/images/:entity/:id/:size/:filename', (req, res, next) => {
this code should be remove as it is part of api now.

2019-02-23 07:46 UTC, ngoyal16 commented on src/server/index.js
> +app.use('/admin-assets', express.static('public/admin-assets', STATIC_OPTIONS));
remove admin code from this. as we have an admin as a separate project

2019-02-23 07:46 UTC, ngoyal16 commented on src/server/index.js
> +app.use('/admin', (req, res) => {
remove admin code from this. as we have an admin as a separate project

2019-02-26 18:02 UTC, vamcart commented
When this PR will be merged?!

I test it on my local machine and it's ok.

Customer Registration.
Customer Activation.
Customer Order Checkout.
Customer Logoff.
Customer Account Page.
New settings for "npm run setup".

Al of this works fine at my local machine.

2019-03-01 07:31 UTC, LuBuss approved these changes

2019-03-01 07:32 UTC, merged